# 람다 서버 배포를 위한 yml

service: openai-chat-api
provider:
  name: aws
  runtime: python3.9
  region: ap-northeast-2  # 한국 리전
functions:
  app:
    handler: main.handler
    events:
      - http:
          path: /
          method: any

# sls deploy 배포 실행
